# Generated by Django 5.1.3 on 2024-11-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Individual')),
                ('price_business', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Business')),
                ('price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по умолчанию')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант товара')),
            ],
        ),
        migrations.CreateModel(
            name='PriceListService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Individual')),
                ('price_business', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Business')),
                ('price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по умолчанию')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория товара')),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgroup', verbose_name='Группа товаров')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'unique_together': {('service_type', 'product_group')},
            },
        ),
    ]
