# Generated by Django 5.1.3 on 2024-11-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pricelist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistproduct',
            name='product_variant',
        ),
        migrations.AlterUniqueTogether(
            name='pricelistservice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pricelistservice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pricelistservice',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='pricelistservice',
            name='service_type',
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('price_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Individual')),
                ('price_business', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для Business')),
                ('price_default', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по умолчанию')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
    ]
