# Generated by Django 5.1.3 on 2024-11-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutting_file', models.FileField(blank=True, null=True, upload_to='cutting_files/%Y/%m/%d/', verbose_name='Файл кроя')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант товара')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'abstract': False,
                'unique_together': {('service_type', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='EdgingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_thickness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Толщина кромки')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант товара')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'abstract': False,
                'unique_together': {('service_type', 'product_variant')},
            },
        ),
        migrations.CreateModel(
            name='FacadeSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coating', models.CharField(max_length=100, verbose_name='Покрытие')),
                ('design', models.CharField(max_length=100, verbose_name='Дизайн')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант товара')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'abstract': False,
                'unique_together': {('service_type', 'product_variant')},
            },
        ),
    ]
