# Generated by Django 5.1.3 on 2024-11-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('specifications', '0002_alter_cuttingspecification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Тип продукта',
                'verbose_name_plural': 'Типы продуктов',
            },
        ),
        migrations.AddField(
            model_name='cuttingspecification',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifications.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='edgingspecification',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifications.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='facadespecification',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specifications.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AlterUniqueTogether(
            name='cuttingspecification',
            unique_together={('service_type', 'product_type', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='edgingspecification',
            unique_together={('service_type', 'product_type', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='facadespecification',
            unique_together={('service_type', 'product_type', 'product_variant')},
        ),
    ]
