# Generated by Django 5.1.3 on 2024-11-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('specifications', '0003_producttype_cuttingspecification_product_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='edgingspecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='edgingspecification',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='edgingspecification',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='edgingspecification',
            name='service_type',
        ),
        migrations.AlterUniqueTogether(
            name='facadespecification',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facadespecification',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='facadespecification',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='facadespecification',
            name='service_type',
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('value', models.CharField(max_length=150, verbose_name='Значение')),
                ('price_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Variant Product')),
            ],
            options={
                'verbose_name': 'Спецификация',
                'verbose_name_plural': 'Спецификации',
            },
        ),
        migrations.DeleteModel(
            name='CuttingSpecification',
        ),
        migrations.DeleteModel(
            name='EdgingSpecification',
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.DeleteModel(
            name='FacadeSpecification',
        ),
    ]
