# Generated by Django 5.1.3 on 2024-11-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('specifications', '0004_alter_edgingspecification_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип спецификации')),
                ('unit_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Тип спецификации',
                'verbose_name_plural': 'Типы спецификаций',
            },
        ),
        migrations.RemoveField(
            model_name='specification',
            name='price_variant',
        ),
        migrations.AddField(
            model_name='specification',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant', verbose_name='Вариант продукта'),
        ),
        migrations.AddField(
            model_name='specification',
            name='specification_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='specifications.specificationtype', verbose_name='Тип спецификации'),
            preserve_default=False,
        ),
    ]
