# Generated by Django 5.1.3 on 2024-11-22 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('specifications', '0005_specificationtype_remove_specification_price_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=150, verbose_name='Значение'),
        ),
        migrations.CreateModel(
            name='ProductVariantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_specifications', to='products.productvariant', verbose_name='Вариант продукта')),
                ('specifications_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specifications.specification', verbose_name='ID спецификации')),
            ],
            options={
                'verbose_name': 'Связь спецификации и варианта товара',
                'verbose_name_plural': 'Связи спецификаций и вариантов товаров',
            },
        ),
        migrations.CreateModel(
            name='TemplateSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='products.producttemplate', verbose_name='Шаблон продукта')),
                ('specifications_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specifications.specification', verbose_name='ID спецификации')),
            ],
            options={
                'verbose_name': 'Связь спецификации и шаблона',
                'verbose_name_plural': 'Связи спецификаций и шаблонов',
            },
        ),
    ]
