# Generated by Django 5.1.3 on 2024-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0006_alter_specification_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=150, verbose_name='Значение'),
        ),
    ]
