# Generated by Django 5.1.3 on 2024-11-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория статусов')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование статуса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание статуса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет статуса (HEX)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='statuses.statuscategory', verbose_name='Категория')),
            ],
        ),
    ]
