# Generated by Django 5.1.3 on 2024-11-19 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price'),
        ('pricelist', '0002_remove_pricelistproduct_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricelist.pricelist', verbose_name='Прайс-лист'),
        ),
    ]
