# Generated by Django 5.1.3 on 2024-11-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0004_alter_orderitem_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='specification_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID спецификации'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='specification_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип спецификации'),
        ),
    ]
