# Generated by Django 5.1.3 on 2024-11-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_specification_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='specification_type',
            new_name='content_type',
        ),
    ]
