# Generated by Django 5.1.3 on 2024-11-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='specification_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID спецификации'),
        ),
    ]
