# Generated by Django 5.1.3 on 2024-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('specifications', '0006_alter_specification_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttemplate',
            options={'verbose_name': 'Шаблон товара', 'verbose_name_plural': 'Шаблоны товаров'},
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='templates', to='specifications.specification', verbose_name='Спецификации'),
        ),
    ]
