# Generated by Django 5.1.3 on 2024-11-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
