# Generated by Django 5.1.3 on 2024-11-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='specifications',
        ),
    ]
