# Generated by Django 5.1.3 on 2024-11-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productvariant_specifications'),
        ('specifications', '0007_alter_specification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='specifications',
            field=models.ManyToManyField(blank=True, related_name='variants', to='specifications.specification', verbose_name='Спецификации'),
        ),
    ]
