# Generated by Django 5.1.3 on 2024-11-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0007_productvariant_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('client_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clienttype', verbose_name='Тип клиента')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.productvariant', verbose_name='Вариант товара')),
            ],
            options={
                'verbose_name': 'Цена для варианта товара',
                'verbose_name_plural': 'Цены для вариантов товара',
                'unique_together': {('product_variant', 'client_type')},
            },
        ),
    ]
